custom:
  project_name: scrapl
  model_name: scrapl_saga_ds_w0_sgd_1e-4_b32
  dataset_name: chirplet_32_32_5_meso
  cpu_batch_size: 3
  use_wandb_cpu: false
  use_wandb_gpu: false

trainer:
  accelerator: gpu
  benchmark: false
  devices: [5]
  max_epochs: 50
  num_sanity_val_steps: 1
  accumulate_grad_batches: 1

data:
  class_path: experiments.data_modules.ThetaDSDataModule
  init_args:
    batch_size: 32

    num_workers: 4
    n_d: 32
    n_s: 32
    n_seeds_per_theta: 5
    n_folds: 5
    use_unique_seeds: true
    use_unique_theta_in_val_test: true

model:
  class_path: experiments.lightning.SCRAPLLightingModule
  init_args:
    model: ../../../configs/models/spectral_2dcnn.yml
    synth: ../../../configs/synths/chirplet_8khz.yml
    loss_func: ../../../configs/losses/scrapl__chirplet__ds_w0.yml

    grad_multiplier: 1e8
    use_pathwise_adam: true
    vr_algo: saga
    update_paths: false
    warmup_paths: false

    use_p_loss: false
    use_train_rand_seed: false
    use_val_rand_seed: false

    use_rand_seed_hat: true

    feature_type: cqt
    cqt_eps: 1e-3
    log_x: false
    log_x_hat: false
    log_val_grads: false

    run_name: scrapl_saga_ds_w0_sgd_1e-4_b32__chirplet_32_32_5_meso

optimizer: ../../../configs/opt/sgd_1e-4.yml
