class_path: experiments.scrapl_loss.SCRAPLLoss
init_args:
  shape: 44100
  J: 12
#  J: 13
  Q1: 8
  Q2: 2
#  J_fr: 3
  J_fr: 5
#  J_fr: 6
  Q_fr: 2
#  Q_fr: 3
#  T: null
  T: 2048
#  T: 4096
#  F: null
  F: 1
  p: 2
  grad_mult: 1e8
  use_pwa: true
  use_saga: true
  sample_all_paths_first: false
  n_theta: 14
  min_prob_frac: 0.0
