class_path: experiments.scrapl_loss.SCRAPLLoss
init_args:
  shape: 44100
  J: 12
  Q1: 8
  Q2: 2
  J_fr: 3
  Q_fr: 2
  T: null
  F: null
#  F: 1
  p: 2
#  grad_mult: 1.0
  grad_mult: 1e8
  use_pwa: true
  use_saga: true
#  use_pwa: false
#  use_saga: false
  sample_all_paths_first: false
  n_theta: 14
  min_prob_frac: 0.0
