seed_everything: 42

custom:
  project_name: scrapl
#  model_name: ploss_724k_adamw_1e-5
#  model_name: mss_meso_log_724k_adamw_1e-5
#  model_name: mss_rev_724k_adamw_1e-5
  model_name: scrapl_saga_pwa_724k_1e-5
#  model_name: jtfs_724k_adamw_1e-5
  dataset_name: theta14_10k_b16
  cpu_batch_size: 2
#  use_wandb_cpu: true
  use_wandb_cpu: false
#  use_wandb_gpu: false
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [5]
  max_epochs: 100
  num_sanity_val_steps: 1
  accumulate_grad_batches: 1
#  accumulate_grad_batches: 2

data:
  class_path: eval_808.data.SeedDataModule
  init_args:
    batch_size: 16
#    batch_size: 8
    n_seeds: 5000
    n_params: 14
    val_split: 0.2
    test_split: 0.2
    randomize_train_seed: false
    num_workers: 8

model:
  class_path: eval_808.lightning.DDSP808LightingModule
  init_args:
    model: spectral_2dcnn_14p.yml
    synth: synth.yml
    fe: fe.yml
#    loss_func: ../losses/mss.yml
#    loss_func: ../losses/mss_meso.yml
#    loss_func: ../losses/mss_meso_log.yml
#    loss_func: ../losses/mss_revisited.yml
#    loss_func: ../eval_808/scat_1d.yml
#    grad_mult: 1e8
    loss_func: ../eval_808/scrapl_saga_pwa.yml
#    loss_func: ../eval_808/jtfst.yml
#    grad_mult: 1e8
    use_p_loss: false
#    loss_func: torch.nn.MSELoss
#    use_p_loss: true
    feature_type: cqt
    cqt_eps: 1e-3
#    scrapl_probs_path: ../data/adaptive_scrapl/scrapl_saga_pwa_1p2M_1e-4__theta14_10k_b16__probs__n_theta_14__n_params_91__n_batches_1__n_iter_20__min_prob_frac_0.0__param_agg_none__seed_42.pt

#    use_warmup: true
#    warmup_n_batches: 1
##    warmup_n_batches: 10
#    warmup_n_iter: 20
#    warmup_param_agg: none

#    run_name: ploss_724k_adamw_1e-5__theta14_10k_b16
#    run_name: mss_meso_log_724k_adamw_1e-5__theta14_10k_b16
#    run_name: mss_rev_724k_adamw_1e-5__theta14_10k_b16
    run_name: scrapl_saga_pwa_724k_1e-5__theta14_10k_b16
#    run_name: jtfs_724k_adamw_1e-5__theta14_10k_b16

#optimizer: ../opt/adam_w_1e-5.yml
optimizer: ../opt/sgd_1e-5.yml
