seed_everything: 42

custom:
  project_name: scrapl
  model_name: mss_mixing__1e-5
#  model_name: scat1d_t256__1e-5
  dataset_name: mixing__no_master__b8
#  dataset_name: mixing_style__no_master__b8
#  dataset_name: mixing__no_master__shift_4096__b8
#  dataset_name: mixing__no_master__shift_8192__b32
  cpu_batch_size: 2
#  use_wandb_cpu: true
  use_wandb_cpu: false
#  use_wandb_gpu: false
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [6]
  max_epochs: 50
  num_sanity_val_steps: 1
  accumulate_grad_batches: 1
#  accumulate_grad_batches: 2
#  gradient_clip_val: 0.5

data:
  class_path: eval_mixing.data_modules.MedleyDBDataModule
  init_args:
#    batch_size: 32
#    batch_size: 16
    batch_size: 8

    sr: 44100
    train_n_samples: 65536
    val_n_samples: 65536
    max_n_tracks: 16
    train_num_examples_per_epoch: 1000
    val_num_examples_per_epoch: 1000
    test_num_examples_per_epoch: 1000
    train_buffer_reload_rate: 1000
    val_buffer_reload_rate: 50000
    test_buffer_reload_rate: 50000
#    train_num_examples_per_epoch: 600
#    val_num_examples_per_epoch: 200
#    test_num_examples_per_epoch: 200
    normalization: peak
    num_workers: 8

#    dataset_dirs:
#      - ../eval_mixing/data/MedleyDB_V2/V2
#    train_indices: [ 0, 4 ]
#    val_indices: [ 0, 4 ]
#    test_indices: [ 0, 4 ]
#    buffer_size_gb: 0.01

    dataset_dirs:
      - /import/c4dm-datasets/MedleyDB_V1/V1
      - /import/c4dm-datasets/MedleyDB_V2/V2
    train_indices: [ 0, 72 ]
    val_indices: [ 72, 96 ]
    test_indices: [ 96, 120 ]
    buffer_size_gb: 4.0

model:
  class_path: eval_mixing.lightning.MixingLightingModule
  init_args:
    encoder: encoder_simple.yml
    emb_dim: 512
#    mixer: mixer_simple.yml
#    n_track_params: 4
#    n_fx_bus_params: 0
#    n_master_bus_params: 0
    mixer: mixer_advanced.yml
    n_track_params: 27
    n_fx_bus_params: 25
    n_master_bus_params: 26
#    loss_func: ../losses/mss.yml
    loss_func: ../losses/mss_mixing.yml
#    loss_func: ../losses/scrapl_saga_pwa.yml
#    loss_func: ../losses/jtfst.yml
#    loss_func: ../losses/scat_1d.yml
#    grad_mult: 1e8

optimizer: ../opt/adam_w_1e-5.yml
#optimizer: ../opt/sgd_1e-5.yml
#optimizer: ../opt/sgd_1e-4.yml
