name: scrapl
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - auraloss
    - black
    - jsonargparse[signatures]>=4.27.7
    - librosa
    - lightning
    - matplotlib
    - nnaudio
    - numpy<2.0.0
    - nvitop
    - pandas
    - pip-chill
    - scipy
    - torch
    - torchaudio
    - torchvision
    - tensorboard
    - uv
    - wandb
    - git+https://github.com/kymatio/kymatio.git

# uv pip install torch lightning torchaudio torchvision auraloss black 'jsonargparse[signatures]>=4.27.7' librosa matplotlib 'numpy<2.0.0' nvitop pandas scipy tensorboard wandb pip-chill nnaudio git+https://github.com/kymatio/kymatio.git
