name: scrapl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cuda-nvcc
  - cuda-nvrtc
  - cuda-version=12.4
  - pip:
    - auraloss
    - black
    - jsonargparse[signatures]>=4.27.7
    - librosa
    - lightning
    - matplotlib
    - msclap
    - nnaudio
    - numpy<2.0.0
    - nvitop
    - pandas
    - pip-chill
    - schedulefree
    - scipy
    - torch
    - torchaudio
    - torchvision
    - tensorboard
    - uv
    - wandb
    - git+https://github.com/kymatio/kymatio.git
    - git+https://github.com/noahgolmant/pytorch-hessian-eigenthings.git

# uv pip install torch lightning torchaudio torchvision auraloss black 'jsonargparse[signatures]' librosa matplotlib msclap numpy nvitop pandas scipy tensorboard wandb pip-chill nnaudio dasp-pytorch pyloudnorm einops hypy-utils git+https://github.com/noahgolmant/pytorch-hessian-eigenthings.git
