name: scrapl
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - auraloss
    - black
    - jsonargparse[signatures]>=4.27.7
    - librosa
    - lightning
    - matplotlib
    - msclap
    - nnaudio
    - numpy<2.0.0
    - nvitop
    - pandas
    - pip-chill
    - schedulefree
    - scipy
    - torch
    - torchaudio
    - torchvision
    - tensorboard
    - uv
    - wandb
    - git+https://github.com/kymatio/kymatio.git
    - git+https://github.com/noahgolmant/pytorch-hessian-eigenthings.git@master#egg=hessian-eigenthings

# uv pip install torch lightning torchaudio torchvision auraloss black 'jsonargparse[signatures]>=4.27.7' librosa matplotlib msclap 'numpy<2.0.0' nvitop pandas scipy tensorboard wandb pip-chill nnaudio git+https://github.com/kymatio/kymatio.git
