name: scrapl
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch=2.1.1
  - torchaudio
  - torchvision
  - cudatoolkit=11.8
  - pip:
    - auraloss
    - black
    - git+https://github.com/kymatio/kymatio.git
    - librosa
    - matplotlib==3.7
    - nnaudio
    - numpy==1.23.5
    - nvitop
    - pandas
    - pytorch-lightning
    - tensorboard
    - wandb
