name: scrapl
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - auraloss
    - black
    - git+https://github.com/kymatio/kymatio.git
    - jsonargparse[signatures]
    - librosa
    - matplotlib==3.7
    - nnaudio
    - numpy==1.23.5
    - pandas
    - pytorch=2.1.1
    - pytorch-lightning
    - torchaudio
    - torchvision
    - tensorboard
    - wandb
