class_path: experiments.synths.AMFMSynth
init_args:
  sr: 8192
  n_samples: 32768
#  f0_hz_min: 512.0
#  f0_hz_max: 512.0
  f0_hz_min: 256.0
  f0_hz_max: 1024.0
  am_hz_min: 2.0
  am_hz_max: 16.0
  fm_hz_min: 256.0
  fm_hz_max: 1024.0
#  fm_hz_min: 2.0
#  fm_hz_max: 16.0
#  mi_am_min: 0.0
#  mi_am_max: 1.0
  mi_am_min: 0.0
  mi_am_max: 0.0
#  mi_fm_min: 0.0
#  mi_fm_max: 0.0
  mi_fm_min: 0.0
  mi_fm_max: 1.0
#  mi_fm_min: 0.0
#  mi_fm_max: 1.0
  theta_am_is_mod_index: false
  theta_fm_is_mod_index: true
  J_cqt: 5
  Q: 12
  hop_len: 256
