class_path: experiments.synth.FastSpeech2Synth
init_args:
#  vocoder_path: ../models/hifigan_t2_v3_generator.pt
  vocoder_path: ../models/lj_v3_generator.pt
  default_text: "Pigs are flying!"
#  default_text: "I want to go to the park with you and test this model."
  wordlist_path: ../data/en_common_words_1k.json
  n_words: 4
  n_frames: 128
  min_pace: 0.8
  max_pace: 1.25
  min_pitch_rate: 0.5
  max_pitch_rate: 2.0
  min_energy_rate: 0.125
  max_energy_rate: 8.0
