seed_everything: 42

custom:
  project_name: scrapl
#  model_name: cnn__ploss
  model_name: cnn__mss__bs512
#  model_name: cnn__jtfst
#  model_name: cnn__scrapl
  dataset_name: chirp_32_32
  cpu_batch_size: 3
  use_wandb_cpu: false
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [7]
  max_epochs: 100
  num_sanity_val_steps: 0
  accumulate_grad_batches: 8

data:
  class_path: experiments.data_modules.ChirpTextureDataModule
  init_args:
    batch_size: 512
    num_workers: 8
    n_densities: 32
#    n_densities: 4
    n_slopes: 32
#    n_slopes: 4
    n_seeds_per_fold: 1
    n_folds: 5
    synth: ../configs/synths/chirp_texture.yml
    feature_type: cqt
    J_cqt: 5
    cqt_eps: 1e-3

model:
  class_path: experiments.lightning.SCRAPLLightingModule
  init_args:
    model: ../configs/models/spectral_2dcnn.yml
    synth: ../configs/synths/chirp_texture.yml
#    loss_func: auraloss.freq.RandomResolutionSTFTLoss  # TODO
    loss_func: auraloss.freq.MultiResolutionSTFTLoss
#    loss_func: ../configs/losses/jtfst.yml
#    loss_func: ../configs/losses/scrapl.yml
    use_p_loss: false
#    use_p_loss: true
#    loss_func: torch.nn.MSELoss
    feature_type: cqt
    J_cqt: 5
    cqt_eps: 1e-3
    log_x: false
    log_x_hat: true

optimizer: ../configs/opt/adam_w.yml
