class_path: experiments.losses.AdaptiveSCRAPLLoss
init_args:
  shape: 32768
  J: 12
  Q1: 8
  Q2: 2
  J_fr: 3
  Q_fr: 2
  T: null
  F: null
  p: 2

  get_path_keys_kw_args:
    sr: 8192

#    am_hz_min: 0.4
#    am_hz_max: 3.9
#    fm_oct_hz_min: 0.4
#    fm_oct_hz_max: 3.9

#    am_hz_min: 0.4
#    am_hz_max: 4.1
#    fm_oct_hz_min: 3.9
#    fm_oct_hz_max: 16.0

#    am_hz_min: 3.9
#    am_hz_max: 16.0
#    fm_oct_hz_min: 0.4
#    fm_oct_hz_max: 4.1

#    am_hz_min: 4.1
#    am_hz_max: 16.0
#    fm_oct_hz_min: 4.1
#    fm_oct_hz_max: 16.0

# =================================
#    am_hz_min: 0.92
#    am_hz_max: 2.81
#    fm_oct_hz_min: 1.2
#    fm_oct_hz_max: 4.1

#    am_hz_min: 2.79
#    am_hz_max: 8.5
#    fm_oct_hz_min: 3.9
#    fm_oct_hz_max: 12.1

#    am_hz_min: 0.92
#    am_hz_max: 2.81
#    fm_oct_hz_min: 3.9
#    fm_oct_hz_max: 12.1

#    am_hz_min: 2.79
#    am_hz_max: 8.5
#    fm_oct_hz_min: 1.2
#    fm_oct_hz_max: 4.1
# =================================

#    am_hz_min: 0.49
#    am_hz_max: 4.0

#    fm_oct_hz_min: 4.0
#    fm_oct_hz_max: 16.0
#    spins: !!set {-1, 0, 1}
#    spins: !!set {0, 1}
#    use_complement: false
#    use_am_fm_union: false
