class_path: experiments.losses.AdaptiveSCRAPLLoss
init_args:
  shape: 32768
  J: 12
  Q1: 8
#  Q1: 12
  Q2: 2
  J_fr: 3
  Q_fr: 2
  T: null
#  T: 2048
#  T: global
  F: null
#  p: 1
  p: 2
  tau: 1.0
  max_prob: 1.0
#  sample_all_paths_first: true
  sample_all_paths_first: false
#  is_trainable: true
  is_trainable: false
#  probs_path: ../data/data_meso_w_p15_norm_mean_elem_F_adj_T_10x.pt
#  probs_path: ../data/data_meso_w_p15_lc_mean_elem_F_adj_T_10x.pt
#  probs_path: ../data/data_meso_w_p15_conv_mean_elem_F_adj_T_10x.pt
#  probs_path: ../data/data_meso_w_p15_ent_mean_elem_F_adj_T_10x.pt
