seed_everything: 42

custom:
  project_name: scrapl
#  model_name: ploss_mse_adamw_1e-4_b32
#  model_name: mse_adamw_1e-4
#  model_name: mss_adamw_1e-4
  model_name: rand_mss_adamw_1e-4_b32
#  model_name: jtfs_adamw_1e-4
#  model_name: scat1d_adamw_1e-4
#  model_name: scat_1d_o1_J12_Q24_T64_adamw_1e-4
#  model_name: clap_adamw_1e-4
#  model_name: wav2vec2tv_adamw_1e-4
#  model_name: scrapl_adamw_1e-5_b32
#  model_name: scrapl_pwa_sgd_1e-5_b32
#  model_name: scrapl_saga_sgd_1e-4_b32
#  model_name: scrapl_saga_sgd_1e-5_b32_a0.25
#  dataset_name: am_hz_fm_mi_32_32_5_meso__f0fm512
#  dataset_name: am_mi_fm_mi_32_32_5_meso__f0fm512
#  dataset_name: am_mi_fm_mi_32_32_5_micro
#  dataset_name: am_mi_fm_mi_32_32_5_meso
#  dataset_name: am_hz_32_32_5_meso__f0_512
#  dataset_name: fm_hz_32_32_5_meso__f0_512_fm_256_512_mi_1
  dataset_name: fm_mi_32_32_5_meso__f0_256_1024_fm_256_1024_mi_0.0_1.0
#  dataset_name: fm_mi_32_32_5_meso__f0_512_1024
#  dataset_name: fm_mi_32_32_5_meso__f0_512_fm_496_528
  cpu_batch_size: 3
#  use_wandb_cpu: true
  use_wandb_cpu: false
#  use_wandb_gpu: false
  use_wandb_gpu: true

trainer:
  accelerator: gpu
  benchmark: false
  devices: [7]
  max_epochs: 50
  num_sanity_val_steps: 5
  accumulate_grad_batches: 1
#  accumulate_grad_batches: 4

data:
  class_path: experiments.data_modules.ThetaDSDataModule
  init_args:
    batch_size: 32

    num_workers: 4
    n_d: 32
    n_s: 32
    n_seeds_per_theta: 5
    n_folds: 5
    use_unique_seeds: true
    use_unique_theta_in_val_test: true

model:
  class_path: experiments.lightning.SCRAPLLightingModule
  init_args:
    model: ../../../configs/models/spectral_2dcnn.yml
    synth: ../../../configs/synths/am_fm_8khz.yml

#    loss_func: ../../../configs/losses/mss.yml
    loss_func: ../../../configs/losses/rand_mss.yml
#    loss_func: ../../../configs/losses/jtfst_dtfa.yml
#    loss_func: ../../../configs/losses/scrapl_adaptive.yml
#    loss_func: ../../../configs/losses/clap.yml

    grad_multiplier: null
#    grad_multiplier: 1e8

    use_pathwise_adam: false
#    use_pathwise_adam: true

    vr_algo: null
#    vr_algo: saga
#    vr_algo: sag
    vr_beta: 1.00

    update_paths: false

    use_p_loss: false
#    use_p_loss: true
#    loss_func: torch.nn.MSELoss

    use_train_rand_seed: false
    use_val_rand_seed: false

#    use_rand_seed_hat: false
    use_rand_seed_hat: true

    feature_type: cqt
    cqt_eps: 1e-3
    log_x: true
    log_x_hat: true
#    log_x_hat: false
#    log_val_grads: true
    log_val_grads: false

#    run_name: scrapl_adamw_1e-5_b32__
#    run_name: scrapl_pwa_sgd_1e-5_b32__
#    run_name: scrapl_saga_sgd_1e-5_b32__
#    run_name: scrapl_saga_sgd_1e-5_b32_a0.25__

optimizer: ../../../configs/opt/adam_w_1e-4.yml
#optimizer: ../../../configs/opt/sgd_1e-4.yml
